#logging.level.root: DEBUG

logging.level:
  org.springframework.web: ${LOG_LEVEL_SPRING_WEB:debug}
  uk.gov.hmcts.reform.sscs: ${LOG_LEVEL_SSCS:debug}
  uk.gov.hmcts.reform.sscs.idam.IdamApiClient: DEBUG
  uk.gov.hmcts.reform.ccd.client.CoreCaseDataApi: DEBUG
  uk.gov.hmcts.reform.ccd.document.EvidenceMetadataDownloadClientApi: DEBUG

feign:
  client:
    config:
      idam-api:
        loggerLevel: full
      core-case-data-api:
        loggerLevel: full
      document-management-metadata-download-api:
        loggerLevel: full

send-letter:
  url: ${SEND_LETTER_SERVICE_BASEURL:false}
