java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
    SEND_LETTER_SERVICE_BASEURL: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
    SEND_LETTER_SERVICE_ENABLED: "true"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-aat.service.core-compute-aat.internal"
    SUBSCRIPTION_NAME: "sscs-evidenceshare-subscription-demo"
    TOPIC_NAME: "sscs-evidenceshare-topic-demo"
    AMQP_HOST: "sscs-servicebus-aat.servicebus.windows.net"
    AMQP_USERNAME: "SendAndListenSharedAccessKey"
    PDF_SERVICE_BASE_URL: ${PDF_SERVICE_BASE_URL}rs/render
    PDF_SERVICE_ACCESS_KEY: ${PDF_SERVICE_ACCESS_KEY}
    PDF_SERVICE_HEALTH_URL: ${PDF_SERVICE_BASE_URL}rs/status
    IDAM_API_URL: ${IDAM_API_URL}
    IDAM_S2S_AUTH_TOTP_SECRET: ${IDAM_S2S_AUTH_TOTP_SECRET}
    IDAM_S2S_AUTH: ${IDAM_S2S_AUTH}
    IDAM_S2S_AUTH_MICROSERVICE: ${IDAM_S2S_AUTH_MICROSERVICE}
    IDAM_SSCS_SYSTEMUPDATE_USER: ${IDAM_SSCS_SYSTEMUPDATE_USER}
    IDAM_SSCS_SYSTEMUPDATE_PASSWORD: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    IDAM_OAUTH2_CLIENT_SECRET: ${IDAM_OAUTH2_CLIENT_SECRET}
    AMQP_PASSWORD: ${AMQP_PASSWORD}
    BUNDLE_STITCHING_ENABLED: "false"
